name: PrChecks
on: [pull_request]

jobs:
  typecheck:
    name: Run Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: yarn hash:validate
      - run: yarn install --production=false
      - run: yarn tsc
      - run: yarn test
